CREATE TABLE IF NOT EXISTS patients (
  id text PRIMARY KEY,
  line_user_id text NOT NULL UNIQUE,
  display_name text NOT NULL,
  urgency text NOT NULL DEFAULT 'green',
  status text NOT NULL DEFAULT 'awaiting_staff',
  age integer,
  procedure text,
  discharge_date text,
  discharge_day integer,
  intake_field text,
  intake_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL,
  updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id text NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  role text NOT NULL,
  body text NOT NULL,
  reason text,
  created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS assessments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  overall integer NOT NULL CHECK (overall BETWEEN 1 AND 5),
  ease integer NOT NULL CHECK (ease BETWEEN 1 AND 5),
  usefulness integer NOT NULL CHECK (usefulness BETWEEN 1 AND 5),
  comment text,
  created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS issues (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id text NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  subject text NOT NULL,
  category text NOT NULL,
  detail text NOT NULL,
  onset text,
  urgency text NOT NULL DEFAULT 'green',
  status text NOT NULL DEFAULT 'unanswered',
  reply_text text,
  created_at text NOT NULL,
  replied_at text
);

CREATE INDEX IF NOT EXISTS messages_patient_id_idx ON messages(patient_id);
CREATE INDEX IF NOT EXISTS patients_updated_at_idx ON patients(updated_at DESC);
CREATE INDEX IF NOT EXISTS issues_status_created_at_idx ON issues(status, created_at DESC);

ALTER TABLE patients ADD COLUMN IF NOT EXISTS discharge_date text;
