CREATE TABLE IF NOT EXISTS patients (
  id text PRIMARY KEY,
  line_user_id text NOT NULL UNIQUE,
  display_name text NOT NULL,
  avatar_url text,
  urgency text NOT NULL DEFAULT 'green',
  status text NOT NULL DEFAULT 'awaiting_staff',
  age integer,
  phone text,
  line_id text,
  procedure text,
  discharge_date text,
  discharge_day integer,
  intake_field text,
  intake_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL,
  updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id text NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  role text NOT NULL,
  body text NOT NULL,
  reason text,
  created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS assessments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  overall integer NOT NULL CHECK (overall BETWEEN 1 AND 5),
  ease integer NOT NULL CHECK (ease BETWEEN 1 AND 5),
  usefulness integer NOT NULL CHECK (usefulness BETWEEN 1 AND 5),
  comment text,
  created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS issues (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id text NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  subject text NOT NULL,
  category text NOT NULL,
  location text,
  detail text NOT NULL,
  onset text,
  urgency text NOT NULL DEFAULT 'green',
  status text NOT NULL DEFAULT 'unanswered',
  image_data text,
  reply_text text,
  created_at text NOT NULL,
  replied_at text
);

CREATE INDEX IF NOT EXISTS messages_patient_id_idx ON messages(patient_id);
CREATE INDEX IF NOT EXISTS patients_updated_at_idx ON patients(updated_at DESC);
CREATE INDEX IF NOT EXISTS issues_status_created_at_idx ON issues(status, created_at DESC);

CREATE TABLE IF NOT EXISTS video_content (
  id text PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  video_url text NOT NULL,
  poster_url text,
  duration_label text,
  views bigint NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  created_at text NOT NULL,
  updated_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS video_content_sort_order_idx ON video_content(sort_order, created_at DESC);

CREATE TABLE IF NOT EXISTS content_page_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS video_view_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id text NOT NULL,
  created_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS content_page_views_created_at_idx ON content_page_views(created_at DESC);
CREATE INDEX IF NOT EXISTS video_view_events_created_at_idx ON video_view_events(created_at DESC);

ALTER TABLE patients ADD COLUMN IF NOT EXISTS discharge_date text;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS avatar_url text;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS line_id text;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS image_data text;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS location text;
